Add local host volume
UffizziCloud/uffizzi_cli pull request #168
Opened 2022-09-13 11:31 UTC by zipofar

2022-09-15 17:23 UTC, artempartos requested changes

2022-09-15 17:23 UTC, artempartos commented on lib/uffizzi/services/compose_file_service.rb
> +      dependency_file_paths.map do |dependency_file_path|
can we simpify it and not use regexp?

something like
```
dependency_file_paths.map do |dependency_file_path|
  dependency_pathname = Pathname.new(dependency_file_path);
  next dependency_file_path if dependency_pathname.absolute?

  expended_path = dependency_pathname.expand_path(compose_file_dir)
  next expended_path.to_s if expended_path.exist?

  raise("Unsupported path #{dependency_file_path}")
end

```

2022-09-15 17:23 UTC, artempartos commented on lib/uffizzi/services/volume_parser_service.rb
> +    def path?(path)
relative?

2022-09-27 13:02 UTC, moklidia commented on lib/uffizzi/services/compose_file_service.rb
> +          parse_env_file(value) if key.to_sym == :env_file
Can we avoid nested map?

2022-09-27 13:02 UTC, moklidia commented on lib/uffizzi/services/volume_parser_service.rb
> +      end
Move the block to a separate method maybe?

2022-10-10 11:10 UTC, moklidia commented on lib/uffizzi/services/volume_parser_service.rb
> +      Uffizzi.ui.say("Volumes '#{volumes}' should be an array") if volumes.is_a?(String)
How about? `unless volumes.is_a?(Array)`

2022-10-10 11:10 UTC, moklidia commented on lib/uffizzi/services/volume_parser_service.rb
> +      /^(\/|\.\/|\.\.\/)/.match?(path) # volume path should start with / or ./ or ../
Should we refator it to not use the regex?

2022-10-10 11:45 UTC, moklidia approved these changes

2022-10-18 07:55 UTC, merged